version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile #Esta opcion serviria si mi dockerfile tuviera otro nombre
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.dev
    # volumes:
    #   - ./backend:/backend
    command: npm run ngrok
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    # volumes:
    #   - ./frontend:/frontend
    command: npm run dev
    restart: unless-stopped